environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_it: ^7.6.0
  injectable: ^2.2.0
  json_annotation: ^4.8.1
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  freezed_annotation: ^2.4.1
  validators2: ^5.0.0
  retrofit: ^4.0.1
  crypto: ^3.0.3
  table_calendar: ^3.0.9
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  retrofit_generator: ^7.0.8

flutter:

  uses-material-design: true

  assets:
    - assets/authentication/
    - assets/shared/